package ru.kuznetsoviv.drools.rules;

import ru.kuznetsoviv.drools.model.Applicant
import ru.kuznetsoviv.drools.model.SuggestedRole;

dialect  "mvel"

global SuggestedRole suggestedRole;

rule "Suggest Manager Role"
    when
        Applicant(experienceInYears > 10)
        Applicant(currentSalary > 1000000 && currentSalary <= 2500000)
    then
        suggestedRole.setRole("Manager");
end

rule "Suggest Senior developer Role"
    when
        Applicant(experienceInYears > 5 && experienceInYears <= 10)
        Applicant(currentSalary > 500000 && currentSalary <= 1500000)
    then
        suggestedRole.setRole("Senior developer");
end

rule "Suggest Developer Role"
    when
        Applicant(experienceInYears > 0 && experienceInYears <= 5)
        Applicant(currentSalary > 200000 && currentSalary <= 1000000)
    then
        suggestedRole.setRole("Developer");
end